services:
  app:
    build: ./app
    command: [uvicorn, src.main:app, --host, 0.0.0.0, --reload]
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.dev.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - type: bind
        source: ./app/src
        target: /opt/simplestTodoApp/app/src
  db:
    image: postgres:bullseye
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.dev.env
